
name: Apply DB Migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run migration
        env:
          PGHOST: ${{ secrets.SUPABASE_HOST }}
          PGPORT: ${{ secrets.SUPABASE_PORT }}
          PGUSER: ${{ secrets.SUPABASE_USER }}
          PGPASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          PGDATABASE: ${{ secrets.SUPABASE_DB }}
        run: |
          psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -f backend/infra/migrations/0002_add_stock_tables.sql -v ON_ERROR_STOP=1

      - name: Done
        run: echo "Migrations applied (or failed with error). Check logs above."
